use base64::Engine;
use crate::models::canvas::CanvasDocument;
use std::path::{Path, PathBuf};
use std::fs;

pub struct CanvasService {
    canvas_dir: PathBuf,
}

impl CanvasService {
    pub fn new(hermes_home: &Path) -> Self {
        Self {
            canvas_dir: hermes_home.join("canvases"),
        }
    }

    fn ensure_dir(&self) -> Result<(), String> {
        if !self.canvas_dir.exists() {
            fs::create_dir_all(&self.canvas_dir)
                .map_err(|e| format!("创建画板目录失败: {e}"))?;
        }
        Ok(())
    }

    pub fn open(&self, path: &str) -> Result<CanvasDocument, String> {
        self.ensure_dir()?;
        let file_path = self.canvas_dir.join(path);
        if !file_path.exists() {
            // Return empty document
            return Ok(CanvasDocument {
                version: 1,
                nodes: Vec::new(),
                connections: Vec::new(),
                metadata: crate::models::canvas::CanvasMeta {
                    title: path.to_string(),
                    created_at: chrono::Utc::now().to_rfc3339(),
                    last_modified: chrono::Utc::now().to_rfc3339(),
                    thumbnail_base64: None,
                },
            });
        }

        let content =
            fs::read_to_string(&file_path).map_err(|e| format!("读取画板文件失败: {e}"))?;
        serde_json::from_str(&content).map_err(|e| format!("解析画板失败: {e}"))
    }

    pub fn save(&self, path: &str, document: &CanvasDocument) -> Result<(), String> {
        self.ensure_dir()?;
        let file_path = self.canvas_dir.join(path);

        // Atomic write: write to temp file, then rename
        let tmp_path = file_path.with_extension("canvas.tmp");
        let json =
            serde_json::to_string_pretty(document).map_err(|e| format!("序列化失败: {e}"))?;
        fs::write(&tmp_path, &json).map_err(|e| format!("写入临时文件失败: {e}"))?;
        fs::rename(&tmp_path, &file_path).map_err(|e| format!("原子写入失败: {e}"))?;

        log::info!("Canvas saved: {path}");
        Ok(())
    }

    pub fn export_png(
        &self,
        path: &str,
        export_path: &str,
        _viewport: Option<(f64, f64, f64, f64)>,
    ) -> Result<(), String> {
        self.ensure_dir()?;
        let file_path = self.canvas_dir.join(path);
        if !file_path.exists() {
            return Err(format!("画板文件 '{path}' 不存在"));
        }

        let content = fs::read_to_string(&file_path)
            .map_err(|e| format!("读取画板文件失败: {e}"))?;
        let doc: CanvasDocument =
            serde_json::from_str(&content).map_err(|e| format!("解析画板失败: {e}"))?;

        // Find base64 PNG thumbnail in metadata (generated by frontend Canvas component)
        if let Some(base64) = &doc.metadata.thumbnail_base64 {
            let data = base64
                .strip_prefix("data:image/png;base64,")
                .unwrap_or(base64);
            let bytes = base64::engine::general_purpose::STANDARD
                .decode(data)
                .map_err(|e| format!("Base64 解码失败: {e}"))?;
            fs::write(export_path, &bytes).map_err(|e| format!("写入PNG失败: {e}"))?;
            log::info!("Canvas exported to PNG: {export_path}");
            Ok(())
        } else {
            // No thumbnail — write a minimal placeholder instead
            Err("画板中没有PNG缩略图数据，请先在Canvas中保存".into())
        }
    }

    pub fn list_canvases(&self) -> Result<Vec<String>, String> {
        self.ensure_dir()?;
        let mut files = Vec::new();
        for entry in fs::read_dir(&self.canvas_dir).map_err(|e| format!("读取画板目录失败: {e}"))?
        {
            let entry = entry.map_err(|e| e.to_string())?;
            let path = entry.path();
            if path.extension().map_or(false, |ext| ext == "json") {
                if let Some(name) = path.file_stem() {
                    files.push(name.to_string_lossy().into_owned());
                }
            }
        }
        Ok(files)
    }

    pub fn delete(&self, path: &str) -> Result<(), String> {
        let file_path = self.canvas_dir.join(path);
        if file_path.exists() {
            fs::remove_file(&file_path).map_err(|e| format!("删除画板失败: {e}"))?;
        }
        Ok(())
    }

    pub fn get_entity_refs(&self, path: &str) -> Result<Vec<String>, String> {
        let doc = self.open(path)?;
        let refs: Vec<String> = doc
            .nodes
            .iter()
            .filter_map(|n| n.entity_ref.clone())
            .collect();
        Ok(refs)
    }

    pub fn link_entity(
        &self,
        path: &str,
        node_id: &str,
        entity_id: Option<&str>,
    ) -> Result<(), String> {
        let mut doc = self.open(path)?;
        for node in &mut doc.nodes {
            if node.id == node_id {
                node.entity_ref = entity_id.map(|s| s.to_string());
                break;
            }
        }
        doc.metadata.last_modified = chrono::Utc::now().to_rfc3339();
        self.save(path, &doc)
    }

    pub fn unlink_all_entities(&self, entity_id: &str) -> Result<u32, String> {
        let mut count = 0u32;
        let canvases = self.list_canvases()?;
        for name in &canvases {
            let path = format!("{}.json", name);
            let mut doc = self.open(&path)?;
            let mut changed = false;
            for node in &mut doc.nodes {
                if node.entity_ref.as_deref() == Some(entity_id) {
                    node.entity_ref = None;
                    count += 1;
                    changed = true;
                }
            }
            if changed {
                doc.metadata.last_modified = chrono::Utc::now().to_rfc3339();
                self.save(&path, &doc)?;
            }
        }
        Ok(count)
    }
}
